#api_uri: http://52.27.230.100/api
#api_uri: http://178.22.122.235/api
base_api_uri: http://localhost:5000
#graphql_api_uri: http://localhost:8088/graphql
#mongo_database_uri: mongodb://localhost:27017/
#mongo_database_name: ostadkar

